encoder_params:
  encoder_type: "ConvEncoder"
  hidden_dims: null

decoder_params:
  decoder_type: "ConvDecoder"
  hidden_dims: null

loss_params:
  loss_type: "cross_entropy_with_kl"
  kl_coeff: 0.01

exp_params:
  # basic info
  model_name: "guassian_vae"
  dataset: "multi_mnist"
  data_path: "data"
  base_model: "vae"
  checkpoint_path: "checkpoints"
  # Hyperparams
  latent_dim: 50
  # Optimisation params
  batch_size: 512 # Better to have a square number
  LR: 0.001
  # data params
  image_shape: 
    - 1
    - 32
    - 32

trainer_params:
  gpus: 1
  max_epochs: 50