encoder_params:
  in_channels: 3
  hidden_dims: null
  latent_dim: 20

decoder_params:
  hidden_dims: null
  latent_dim: 20

loss_params:
  kl_coeff: 0.01

exp_params:
  model_name: 'vanilla_vae'
  dataset: mnist
  data_path: "data"
  batch_size: 256 # Better to have a square number
  LR: 0.001
  template: "default vae"

trainer_params:
  gpus: 1
  max_epochs: 30